// types/supabase.ts

import { Database } from './database.types'; // Assuming you might generate types from Supabase CLI later

// Define types for the public schema tables

export type UserRole = 
  | 'founder'
  | 'ceo'
  | 'cto'
  | 'designer'
  | 'ui_ux'
  | 'engineer'
  | 'frontend_engineer'
  | 'backend_engineer'
  | 'fullstack_engineer'
  | 'mobile_engineer'
  | 'data_engineer'
  | 'ml_engineer'
  | 'product_manager'
  | 'project_manager'
  | 'marketing'
  | 'sales'
  | 'devops'
  | 'qa_tester'
  | 'community_manager'
  | 'support'
  | 'finance'
  | 'hr'
  | 'other';

export type Profile = {
  id: string; // UUID from auth.users
  created_at: string; // timestamptz
  updated_at: string; // timestamptz
  username: string | null; // text, UNIQUE
  full_name: string | null; // text
  avatar_url: string | null; // text
  email: string | null; // text, UNIQUE (can be synced from auth.users)
  role: UserRole; // user_role
};

export type Workspace = {
  id: string; // UUID, gen_random_uuid()
  created_at: string; // timestamptz
  updated_at: string; // timestamptz
  name: string; // text, NOT NULL
  slug: string | null; // text, UNIQUE
  owner_id: string; // UUID, REFERENCES public.profiles(id)
  description: string | null; // text
  logo_url: string | null; // text
};

export type WorkspaceMember = {
  id: string; // UUID, gen_random_uuid()
  created_at: string; // timestamptz
  user_id: string; // UUID, REFERENCES public.profiles(id)
  workspace_id: string; // UUID, REFERENCES public.workspaces(id)
  role: 'owner' | 'admin' | 'member' | 'viewer'; // text, NOT NULL, DEFAULT 'member'
  status: 'active' | 'inactive' | 'suspended'; // text, NOT NULL, DEFAULT 'active'
};

export type WorkspaceInvite = {
  id: string; // UUID, gen_random_uuid()
  created_at: string; // timestamptz
  workspace_id: string; // UUID, REFERENCES public.workspaces(id)
  invited_by_user_id: string; // UUID, REFERENCES public.profiles(id)
  invitee_email: string; // text, NOT NULL
  token: string; // UUID, gen_random_uuid(), UNIQUE
  role: 'owner' | 'admin' | 'member' | 'viewer'; // text, NOT NULL, DEFAULT 'member'
  expires_at: string | null; // timestamptz
  status: 'pending' | 'accepted' | 'declined' | 'expired'; // text, NOT NULL, DEFAULT 'pending'
};

export type WorkspaceSetting = {
  id: string; // UUID, gen_random_uuid()
  workspace_id: string; // UUID, UNIQUE, REFERENCES public.workspaces(id)
  plan: 'free' | 'pro' | 'enterprise'; // text, DEFAULT 'free'
  onboarding_complete: boolean; // boolean, DEFAULT false
  data: Record<string, any>; // jsonb, DEFAULT '{}'
  created_at: string; // timestamptz
  updated_at: string; // timestamptz
};

// You can also define a combined type for the entire database schema
// This is often generated by the Supabase CLI, but can be manually defined
// if you prefer or for specific use cases.
export type Tables = {
  profiles: Profile;
  workspaces: Workspace;
  workspace_members: WorkspaceMember;
  workspace_invites: WorkspaceInvite;
  workspace_settings: WorkspaceSetting;
};

// Example of how you might use these types with the Supabase client
// import { createClient } from '@supabase/supabase-js';
// const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
// type Database = {
//   public: {
//     Tables: Tables;
//     Views: {
//       [_ in never]: never;
//     };
//     Functions: {
//       [_ in never]: never;
//     };
//     Enums: {
//       [_ in never]: never;
//     };
//   };
// };
